version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - github-actions
- package-ecosystem: nuget
  directory: /
  reviewers:
  - joaope
  schedule:
    interval: daily
  labels:
  - dependencies
  - dotnet
