name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.dotnet }})
    runs-on: ${{ matrix.os }}
    concurrency: publish-${{ github.ref }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dotnet: ['6.x']
        
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - run: dotnet build
    - run: dotnet test --no-build --verbosity normal
