name: 'Publish Pre-Release'

on:
  release:
    types:
      - prereleased

jobs:
  publish:
    name: 'Publish Pre-Release'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      - run: dotnet pack ./src/LogSnag -c Release -o ./artifacts 
      - run: dotnet pack ./src/LogSnag.Extensions.Microsoft.DependencyInjection -c Release -o ./artifacts
      - run: dotnet nuget push ./artifacts/*.nupkg --source https://www.myget.org/F/logsnag/api/v3/index.json --api-key ${{ secrets.MYGET_API_KEY }}